# Copyright 1998-2024, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# This file was automatically generated from gedcom-5.5.1.grammar
# by Paul Johnson
# on Sun Jul 21 17:46:58 2024

# Do not edit this file.
# Edit gedcom-5.5.1.grammar if changes need to be made.
# Edit parse_grammar or Makefile.PL to increase the legibility of this file.
# (Removal of the leading spaces nearly halves the size of the file.)

# Version 1.22 - 15th November 2019

package Gedcom::Grammar_5_5_1;

use strict;
require 5.005;

use vars qw($VERSION $grammar);
$VERSION = 1.22;

$grammar = bless( {
fh => \*Symbol::GEN0,
file => 'gedcom-5.5.1.grammar',
gedcom => {},
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => 0,
line => 3,
max => 1,
min => 1,
pointer => !!0,
value => '<<HEADER>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => 0,
line => 4,
max => 1,
min => 0,
pointer => !!0,
value => '<<SUBMISSION_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => 0,
line => 5,
max => 'M',
min => 0,
pointer => !!0,
value => '<<RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 6,
max => 1,
min => 1,
tag => 'TRLR'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 1,
structure => 'GEDCOM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 12,
max => 1,
min => 0,
pointer => !!0,
tag => 'VERS',
value => '<VERSION_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 13,
max => 1,
min => 0,
pointer => !!0,
tag => 'NAME',
value => '<NAME_OF_PRODUCT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 15,
max => 1,
min => 0,
pointer => !!0,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 14,
max => 1,
min => 0,
pointer => !!0,
tag => 'CORP',
value => '<NAME_OF_BUSINESS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 17,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<PUBLICATION_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+4',
line => 19,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<COPYRIGHT_SOURCE_DATA>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+4',
line => 20,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<COPYRIGHT_SOURCE_DATA>'
}, 'Gedcom::Grammar' )
],
level => '+3',
line => 18,
max => 1,
min => 0,
pointer => !!0,
tag => 'COPR',
value => '<COPYRIGHT_SOURCE_DATA>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 16,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATA',
value => '<NAME_OF_SOURCE_DATA>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 11,
max => 1,
min => 1,
pointer => !!0,
tag => 'SOUR',
value => '<APPROVED_SYSTEM_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 21,
max => 1,
min => 0,
pointer => !!0,
tag => 'DEST',
value => '<RECEIVING_SYSTEM_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 23,
max => 1,
min => 0,
pointer => !!0,
tag => 'TIME',
value => '<TIME_VALUE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 22,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<TRANSMISSION_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 24,
max => 1,
min => 1,
pointer => !!1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 25,
max => 1,
min => 0,
pointer => !!1,
tag => 'SUBN',
value => '<XREF:SUBN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 26,
max => 1,
min => 0,
pointer => !!0,
tag => 'FILE',
value => '<FILE_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 27,
max => 1,
min => 0,
pointer => !!0,
tag => 'COPR',
value => '<COPYRIGHT_GEDCOM_FILE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 29,
max => 1,
min => 1,
pointer => !!0,
tag => 'VERS',
value => '<VERSION_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 30,
max => 1,
min => 1,
pointer => !!0,
tag => 'FORM',
value => '<GEDCOM_FORM>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 28,
max => 1,
min => 1,
tag => 'GEDC'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 32,
max => 1,
min => 0,
pointer => !!0,
tag => 'VERS',
value => '<VERSION_NUMBER>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 31,
max => 1,
min => 1,
pointer => !!0,
tag => 'CHAR',
value => '<CHARACTER_SET>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 33,
max => 1,
min => 0,
pointer => !!0,
tag => 'LANG',
value => '<LANGUAGE_OF_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 35,
max => 1,
min => 1,
pointer => !!0,
tag => 'FORM',
value => '<PLACE_HIERARCHY>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 34,
max => 1,
min => 0,
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 37,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<GEDCOM_CONTENT_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+2',
line => 38,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<GEDCOM_CONTENT_DESCRIPTION>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 36,
max => 1,
min => 0,
pointer => !!0,
tag => 'NOTE',
value => '<GEDCOM_CONTENT_DESCRIPTION>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 10,
max => 1,
min => 1,
tag => 'HEAD'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 8,
structure => 'HEADER'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 43,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<FAM_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 45,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 47,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<MULTIMEDIA_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 49,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<NOTE_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 51,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<REPOSITORY_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 53,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<SOURCE_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 55,
max => 1,
min => 1,
pointer => !!0,
selection => 1,
value => '<<SUBMITTER_RECORD>>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 41,
selection => 1,
structure => 'RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 61,
max => 1,
min => 0,
pointer => !!0,
tag => 'RESN',
value => '<RESTRICTION_NOTICE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 62,
max => 'M',
min => 0,
pointer => !!0,
value => '<<FAMILY_EVENT_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 63,
max => 1,
min => 0,
pointer => !!1,
tag => 'HUSB',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 64,
max => 1,
min => 0,
pointer => !!1,
tag => 'WIFE',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 65,
max => 'M',
min => 0,
pointer => !!1,
tag => 'CHIL',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 66,
max => 1,
min => 0,
pointer => !!0,
tag => 'NCHI',
value => '<COUNT_OF_CHILDREN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 67,
max => 'M',
min => 0,
pointer => !!1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 68,
max => 'M',
min => 0,
pointer => !!0,
value => '<<LDS_SPOUSE_SEALING>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 70,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 69,
max => 'M',
min => 0,
pointer => !!0,
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 71,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 72,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 73,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 74,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 75,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 60,
max => 1,
min => 1,
tag => 'FAM',
xref => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 58,
structure => 'FAM_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 81,
max => 1,
min => 0,
pointer => !!0,
tag => 'RESN',
value => '<RESTRICTION_NOTICE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 82,
max => 'M',
min => 0,
pointer => !!0,
value => '<<PERSONAL_NAME_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 83,
max => 1,
min => 0,
pointer => !!0,
tag => 'SEX',
value => '<SEX_VALUE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 84,
max => 'M',
min => 0,
pointer => !!0,
value => '<<INDIVIDUAL_EVENT_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 85,
max => 'M',
min => 0,
pointer => !!0,
value => '<<INDIVIDUAL_ATTRIBUTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 86,
max => 'M',
min => 0,
pointer => !!0,
value => '<<LDS_INDIVIDUAL_ORDINANCE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 87,
max => 'M',
min => 0,
pointer => !!0,
value => '<<CHILD_TO_FAMILY_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 88,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SPOUSE_TO_FAMILY_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 89,
max => 'M',
min => 0,
pointer => !!1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 90,
max => 'M',
min => 0,
pointer => !!0,
value => '<<ASSOCIATION_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 91,
max => 'M',
min => 0,
pointer => !!1,
tag => 'ALIA',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 92,
max => 'M',
min => 0,
pointer => !!1,
tag => 'ANCI',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 93,
max => 'M',
min => 0,
pointer => !!1,
tag => 'DESI',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 94,
max => 1,
min => 0,
pointer => !!0,
tag => 'RFN',
value => '<PERMANENT_RECORD_FILE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 95,
max => 1,
min => 0,
pointer => !!0,
tag => 'AFN',
value => '<ANCESTRAL_FILE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 97,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 96,
max => 'M',
min => 0,
pointer => !!0,
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 98,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 99,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 100,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 101,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 102,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 80,
max => 1,
min => 1,
tag => 'INDI',
xref => '<XREF:INDI>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 78,
structure => 'INDIVIDUAL_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 110,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<SOURCE_MEDIA_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 109,
max => 1,
min => 1,
pointer => !!0,
tag => 'FORM',
value => '<MULTIMEDIA_FORMAT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 111,
max => 1,
min => 0,
pointer => !!0,
tag => 'TITL',
value => '<DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 108,
max => 'M',
min => 1,
pointer => !!0,
tag => 'FILE',
value => '<MULTIMEDIA_FILE_REFN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 113,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 112,
max => 'M',
min => 0,
pointer => !!0,
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 114,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 115,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 116,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 117,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 107,
max => 1,
min => 1,
tag => 'OBJE',
xref => '<XREF:OBJE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 105,
structure => 'MULTIMEDIA_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 123,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 124,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 126,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 125,
max => 'M',
min => 0,
pointer => !!0,
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 127,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 128,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 129,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 122,
max => 1,
min => 1,
pointer => !!0,
tag => 'NOTE',
value => '<SUBMITTER_TEXT>',
xref => '<XREF:NOTE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 120,
structure => 'NOTE_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 135,
max => 1,
min => 1,
pointer => !!0,
tag => 'NAME',
value => '<NAME_OF_REPOSITORY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 136,
max => 1,
min => 0,
pointer => !!0,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 137,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 139,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 138,
max => 'M',
min => 0,
pointer => !!0,
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 140,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 141,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 134,
max => 1,
min => 1,
tag => 'REPO',
xref => '<XREF:REPO>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 132,
structure => 'REPOSITORY_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 149,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_PERIOD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 150,
max => 1,
min => 0,
pointer => !!0,
tag => 'PLAC',
value => '<SOURCE_JURISDICTION_PLACE>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 148,
max => 'M',
min => 0,
pointer => !!0,
tag => 'EVEN',
value => '<EVENTS_RECORDED>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 151,
max => 1,
min => 0,
pointer => !!0,
tag => 'AGNC',
value => '<RESPONSIBLE_AGENCY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 152,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 147,
max => 1,
min => 0,
tag => 'DATA'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 154,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<SOURCE_ORIGINATOR>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 155,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<SOURCE_ORIGINATOR>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 153,
max => 1,
min => 0,
pointer => !!0,
tag => 'AUTH',
value => '<SOURCE_ORIGINATOR>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 157,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<SOURCE_DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 158,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<SOURCE_DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 156,
max => 1,
min => 0,
pointer => !!0,
tag => 'TITL',
value => '<SOURCE_DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 159,
max => 1,
min => 0,
pointer => !!0,
tag => 'ABBR',
value => '<SOURCE_FILED_BY_ENTRY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 161,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<SOURCE_PUBLICATION_FACTS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 162,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<SOURCE_PUBLICATION_FACTS>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 160,
max => 1,
min => 0,
pointer => !!0,
tag => 'PUBL',
value => '<SOURCE_PUBLICATION_FACTS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 164,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 165,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 163,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEXT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 166,
max => 1,
min => 0,
pointer => !!0,
value => '<<SOURCE_REPOSITORY_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 168,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 167,
max => 'M',
min => 0,
pointer => !!0,
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 169,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 170,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 171,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 172,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 146,
max => 1,
min => 1,
tag => 'SOUR',
xref => '<XREF:SOUR>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 144,
structure => 'SOURCE_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 178,
max => 1,
min => 0,
pointer => !!1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 179,
max => 1,
min => 0,
pointer => !!0,
tag => 'FAMF',
value => '<NAME_OF_FAMILY_FILE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 180,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 181,
max => 1,
min => 0,
pointer => !!0,
tag => 'ANCE',
value => '<GENERATIONS_OF_ANCESTORS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 182,
max => 1,
min => 0,
pointer => !!0,
tag => 'DESC',
value => '<GENERATIONS_OF_DESCENDANTS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 183,
max => 1,
min => 0,
pointer => !!0,
tag => 'ORDI',
value => '<ORDINANCE_PROCESS_FLAG>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 184,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 185,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 186,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 177,
max => 1,
min => 1,
tag => 'SUBN',
xref => '<XREF:SUBN>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 175,
structure => 'SUBMISSION_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 192,
max => 1,
min => 1,
pointer => !!0,
tag => 'NAME',
value => '<SUBMITTER_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 193,
max => 1,
min => 0,
pointer => !!0,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 194,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 195,
max => 3,
min => 0,
pointer => !!0,
tag => 'LANG',
value => '<LANGUAGE_PREFERENCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 196,
max => 1,
min => 0,
pointer => !!0,
tag => 'RFN',
value => '<SUBMITTER_REGISTERED_RFN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 197,
max => 1,
min => 0,
pointer => !!0,
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 198,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 199,
max => 1,
min => 0,
pointer => !!0,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 191,
max => 1,
min => 1,
tag => 'SUBM',
xref => '<XREF:SUBM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 189,
structure => 'SUBMITTER_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 205,
max => 3,
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<ADDRESS_LINE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 206,
max => 1,
min => 0,
pointer => !!0,
tag => 'ADR1',
value => '<ADDRESS_LINE1>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 207,
max => 1,
min => 0,
pointer => !!0,
tag => 'ADR2',
value => '<ADDRESS_LINE2>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 208,
max => 1,
min => 0,
pointer => !!0,
tag => 'ADR3',
value => '<ADDRESS_LINE3>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 209,
max => 1,
min => 0,
pointer => !!0,
tag => 'CITY',
value => '<ADDRESS_CITY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 210,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAE',
value => '<ADDRESS_STATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 211,
max => 1,
min => 0,
pointer => !!0,
tag => 'POST',
value => '<ADDRESS_POSTAL_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 212,
max => 1,
min => 0,
pointer => !!0,
tag => 'CTRY',
value => '<ADDRESS_COUNTRY>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 204,
max => 1,
min => 0,
pointer => !!0,
tag => 'ADDR',
value => '<ADDRESS_LINE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 213,
max => 3,
min => 0,
pointer => !!0,
tag => 'PHON',
value => '<PHONE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 214,
max => 3,
min => 0,
pointer => !!0,
tag => 'EMAIL',
value => '<ADDRESS_EMAIL>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 215,
max => 3,
min => 0,
pointer => !!0,
tag => 'FAX',
value => '<ADDRESS_FAX>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 216,
max => 3,
min => 0,
pointer => !!0,
tag => 'WWW',
value => '<ADDRESS_WEB_PAGE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 202,
structure => 'ADDRESS_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 222,
max => 1,
min => 1,
pointer => !!0,
tag => 'RELA',
value => '<RELATION_IS_DESCRIPTOR>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 223,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 224,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 221,
max => 1,
min => 0,
pointer => !!1,
tag => 'ASSO',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 219,
structure => 'ASSOCIATION_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 231,
max => 1,
min => 0,
pointer => !!0,
tag => 'TIME',
value => '<TIME_VALUE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 230,
max => 1,
min => 1,
pointer => !!0,
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 232,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 229,
max => 1,
min => 1,
tag => 'CHAN'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 227,
structure => 'CHANGE_DATE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 238,
max => 1,
min => 0,
pointer => !!0,
tag => 'PEDI',
value => '<PEDIGREE_LINKAGE_TYPE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 239,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAT',
value => '<CHILD_LINKAGE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 240,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 237,
max => 1,
min => 1,
pointer => !!1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 235,
structure => 'CHILD_TO_FAMILY_LINK'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 245,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<EVENT_DESCRIPTOR>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 246,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_VALUE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 247,
max => 1,
min => 0,
pointer => !!0,
value => '<<PLACE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 248,
max => 1,
min => 0,
pointer => !!0,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 249,
max => 1,
min => 0,
pointer => !!0,
tag => 'AGNC',
value => '<RESPONSIBLE_AGENCY>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 250,
max => 1,
min => 0,
pointer => !!0,
tag => 'RELI',
value => '<RELIGIOUS_AFFILIATION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 251,
max => 1,
min => 0,
pointer => !!0,
tag => 'CAUS',
value => '<CAUSE_OF_EVENT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 252,
max => 1,
min => 0,
pointer => !!0,
tag => 'RESN',
value => '<RESTRICTION_NOTICE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 253,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 254,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 255,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 243,
structure => 'EVENT_DETAIL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 260,
max => 1,
min => 1,
pointer => !!0,
tag => 'AGE',
value => '<AGE_AT_EVENT>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 259,
max => 1,
min => 0,
tag => 'HUSB'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 262,
max => 1,
min => 1,
pointer => !!0,
tag => 'AGE',
value => '<AGE_AT_EVENT>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 261,
max => 1,
min => 0,
tag => 'WIFE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 263,
max => 1,
min => 0,
pointer => !!0,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 258,
structure => 'FAMILY_EVENT_DETAIL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 270,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 269,
max => 1,
min => 1,
tag => 'ANUL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 273,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 272,
max => 1,
min => 1,
tag => 'CENS'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 276,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 275,
max => 1,
min => 1,
tag => 'DIV'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 279,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 278,
max => 1,
min => 1,
tag => 'DIVF'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 282,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 281,
max => 1,
min => 1,
tag => 'ENGA'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 285,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 284,
max => 1,
min => 1,
tag => 'MARB'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 288,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 287,
max => 1,
min => 1,
tag => 'MARC'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 291,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 290,
max => 1,
min => 1,
tag => 'MARR'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 294,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 293,
max => 1,
min => 1,
tag => 'MARL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 297,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 296,
max => 1,
min => 1,
tag => 'MARS'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 300,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 299,
max => 1,
min => 1,
tag => 'RESI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 303,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<FAMILY_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 302,
max => 1,
min => 1,
pointer => !!0,
tag => 'EVEN',
value => '<EVENT_DISCRIPTOR>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 266,
selection => 1,
structure => 'FAMILY_EVENT_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 312,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 311,
max => 1,
min => 1,
pointer => !!0,
tag => 'CAST',
value => '<CASTE_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 315,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<PHYSICAL_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 316,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<PHYSICAL_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 317,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 314,
max => 1,
min => 1,
pointer => !!0,
tag => 'DSCR',
value => '<PHYSICAL_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 320,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 319,
max => 1,
min => 1,
pointer => !!0,
tag => 'EDUC',
value => '<SCHOLASTIC_ACHIEVEMENT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 323,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 322,
max => 1,
min => 1,
pointer => !!0,
tag => 'IDNO',
value => '<NATIONAL_ID_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 326,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 325,
max => 1,
min => 1,
pointer => !!0,
tag => 'NATI',
value => '<NATIONAL_OR_TRIBAL_ORIGIN>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 329,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 328,
max => 1,
min => 1,
pointer => !!0,
tag => 'NCHI',
value => '<COUNT_OF_CHILDREN>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 332,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 331,
max => 1,
min => 1,
pointer => !!0,
tag => 'NMR',
value => '<COUNT_OF_MARRIAGES>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 335,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 334,
max => 1,
min => 1,
pointer => !!0,
tag => 'OCCU',
value => '<OCCUPATION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 338,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 337,
max => 1,
min => 1,
pointer => !!0,
tag => 'PROP',
value => '<POSSESSIONS>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 341,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 340,
max => 1,
min => 1,
pointer => !!0,
tag => 'RELI',
value => '<RELIGIOUS_AFFILIATION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 344,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 343,
max => 1,
min => 1,
tag => 'RESI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 347,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 346,
max => 1,
min => 0,
pointer => !!0,
tag => 'SSN',
value => '<SOCIAL_SECURITY_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 350,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 349,
max => 1,
min => 1,
pointer => !!0,
tag => 'TITL',
value => '<NOBILITY_TYPE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 353,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 352,
max => 1,
min => 1,
pointer => !!0,
tag => 'FACT',
value => '<ATTRIBUTE_DESCRIPTOR>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 308,
selection => 1,
structure => 'INDIVIDUAL_ATTRIBUTE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 358,
max => 1,
min => 1,
pointer => !!0,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 359,
max => 1,
min => 0,
pointer => !!0,
tag => 'AGE',
value => '<AGE_AT_EVENT>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 357,
structure => 'INDIVIDUAL_EVENT_DETAIL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 366,
max => 1,
min => 0,
pointer => !!0,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 367,
max => 1,
min => 0,
pointer => !!1,
selection => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 365,
max => 1,
min => 1,
tag => 'BIRT'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 370,
max => 1,
min => 0,
pointer => !!0,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 371,
max => 1,
min => 0,
pointer => !!1,
selection => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 369,
max => 1,
min => 1,
tag => 'CHR'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 374,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 373,
max => 1,
min => 1,
tag => 'DEAT'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 377,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 376,
max => 1,
min => 1,
tag => 'BURI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 380,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 379,
max => 1,
min => 1,
tag => 'CREM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 383,
max => 1,
min => 0,
pointer => !!0,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+2',
line => 385,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
tag => 'ADOP',
value => '<ADOPTED_BY_WHICH_PARENT>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 384,
max => 1,
min => 0,
pointer => !!1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 382,
max => 1,
min => 1,
tag => 'ADOP'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 388,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 387,
max => 1,
min => 1,
tag => 'BAPM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 391,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 390,
max => 1,
min => 1,
tag => 'BARM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 394,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 393,
max => 1,
min => 1,
tag => 'BASM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 397,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 396,
max => 1,
min => 1,
tag => 'BLES'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 400,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 399,
max => 1,
min => 1,
tag => 'CHRA'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 403,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 402,
max => 1,
min => 1,
tag => 'CONF'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 406,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 405,
max => 1,
min => 1,
tag => 'FCOM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 409,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 408,
max => 1,
min => 1,
tag => 'ORDN'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 412,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 411,
max => 1,
min => 1,
tag => 'NATU'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 415,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 414,
max => 1,
min => 1,
tag => 'EMIG'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 418,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 417,
max => 1,
min => 1,
tag => 'IMMI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 421,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 420,
max => 1,
min => 1,
tag => 'CENS'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 424,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 423,
max => 1,
min => 1,
tag => 'PROB'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 427,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 426,
max => 1,
min => 1,
tag => 'WILL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 430,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 429,
max => 1,
min => 1,
tag => 'GRAD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 433,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 432,
max => 1,
min => 1,
tag => 'RETI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 436,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
value => '<<INDIVIDUAL_EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 435,
max => 1,
min => 1,
tag => 'EVEN'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 362,
selection => 1,
structure => 'INDIVIDUAL_EVENT_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 444,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 445,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 446,
max => 1,
min => 0,
pointer => !!0,
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 448,
max => 1,
min => 1,
pointer => !!0,
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 447,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAT',
value => '<LDS_BAPTISM_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 449,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 450,
max => 'M',
min => 0,
pointer => !!0,
selection => 1,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 443,
max => 1,
min => 1,
tag => 'BAPL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 453,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 454,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 455,
max => 1,
min => 0,
pointer => !!0,
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 457,
max => 1,
min => 1,
pointer => !!0,
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 456,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAT',
value => '<LDS_BAPTISM_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 458,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 459,
max => 'M',
min => 0,
pointer => !!0,
selection => 1,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 452,
max => 1,
min => 1,
tag => 'CONL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 462,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 463,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 464,
max => 1,
min => 0,
pointer => !!0,
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 466,
max => 1,
min => 1,
pointer => !!0,
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 465,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAT',
value => '<LDS_ENDOWMENT_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 467,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 468,
max => 'M',
min => 0,
pointer => !!0,
selection => 1,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 461,
max => 1,
min => 1,
tag => 'ENDL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 471,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 472,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 473,
max => 1,
min => 0,
pointer => !!0,
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 474,
max => 1,
min => 1,
pointer => !!1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 476,
max => 1,
min => 1,
pointer => !!0,
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 475,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAT',
value => '<LDS_CHILD_SEALING_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 477,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 478,
max => 'M',
min => 0,
pointer => !!0,
selection => 1,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 470,
max => 1,
min => 1,
tag => 'SLGC'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 440,
selection => 1,
structure => 'LDS_INDIVIDUAL_ORDINANCE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 485,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 486,
max => 1,
min => 0,
pointer => !!0,
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 487,
max => 1,
min => 0,
pointer => !!0,
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 489,
max => 1,
min => 1,
pointer => !!0,
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 488,
max => 1,
min => 0,
pointer => !!0,
tag => 'STAT',
value => '<LDS_SPOUSE_SEALING_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 490,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 491,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 484,
max => 1,
min => 1,
tag => 'SLGS'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 482,
structure => 'LDS_SPOUSE_SEALING'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 497,
max => 1,
min => 1,
pointer => !!1,
selection => 1,
tag => 'OBJE',
value => '<XREF:OBJE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 502,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<SOURCE_MEDIA_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 501,
max => 1,
min => 1,
pointer => !!0,
tag => 'FORM',
value => '<MULTIMEDIA_FORMAT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+2',
line => 503,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
tag => 'TITL',
value => '<DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 500,
max => 'M',
min => 1,
pointer => !!0,
tag => 'FILE',
value => '<MULTIMEDIA_FILE_REFN>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 499,
max => 1,
min => 1,
tag => 'OBJE'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 494,
selection => 1,
structure => 'MULTIMEDIA_LINK'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 510,
max => 1,
min => 1,
pointer => !!1,
selection => 1,
tag => 'NOTE',
value => '<XREF:NOTE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 513,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 514,
max => 'M',
min => 0,
pointer => !!0,
selection => 1,
tag => 'CONT',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 512,
max => 1,
min => 1,
pointer => !!0,
tag => 'NOTE',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 507,
selection => 1,
structure => 'NOTE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 520,
max => 1,
min => 0,
pointer => !!0,
tag => 'NPFX',
value => '<NAME_PIECE_PREFIX>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 521,
max => 1,
min => 0,
pointer => !!0,
tag => 'GIVN',
value => '<NAME_PIECE_GIVEN>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 522,
max => 1,
min => 0,
pointer => !!0,
tag => 'NICK',
value => '<NAME_PIECE_NICKNAME>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 523,
max => 1,
min => 0,
pointer => !!0,
tag => 'SPFX',
value => '<NAME_PIECE_SURNAME_PREFIX>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 524,
max => 1,
min => 0,
pointer => !!0,
tag => 'SURN',
value => '<NAME_PIECE_SURNAME>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 525,
max => 1,
min => 0,
pointer => !!0,
tag => 'NSFX',
value => '<NAME_PIECE_SUFFIX>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 526,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 527,
max => 'M',
min => 0,
pointer => !!0,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 518,
structure => 'PERSONAL_NAME_PIECES'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 533,
max => 1,
min => 0,
pointer => !!0,
tag => 'TYPE',
value => '<NAME_TYPE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 534,
max => 1,
min => 0,
pointer => !!0,
value => '<<PERSONAL_NAME_PIECES>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 536,
max => 1,
min => 1,
pointer => !!0,
tag => 'TYPE',
value => '<PHONETIC_TYPE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 537,
max => 1,
min => 0,
pointer => !!0,
value => '<<PERSONAL_NAME_PIECES>>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 535,
max => 'M',
min => 0,
pointer => !!0,
tag => 'FONE',
value => '<NAME_PHONETIC_VARIATION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 539,
max => 1,
min => 1,
pointer => !!0,
tag => 'TYPE',
value => '<ROMANIZED_TYPE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+2',
line => 540,
max => 1,
min => 0,
pointer => !!0,
value => '<<PERSONAL_NAME_PIECES>>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 538,
max => 'M',
min => 0,
pointer => !!0,
tag => 'ROMN',
value => '<NAME_ROMANIZED_VARIATION>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 532,
max => 1,
min => 1,
pointer => !!0,
tag => 'NAME',
value => '<NAME_PERSONAL>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 530,
structure => 'PERSONAL_NAME_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 546,
max => 1,
min => 0,
pointer => !!0,
tag => 'FORM',
value => '<PLACE_HIERARCHY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 548,
max => 1,
min => 1,
pointer => !!0,
tag => 'TYPE',
value => '<PHONETIC_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 547,
max => 'M',
min => 0,
pointer => !!0,
tag => 'FONE',
value => '<PLACE_PHONETIC_VARIATION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 550,
max => 1,
min => 1,
pointer => !!0,
tag => 'TYPE',
value => '<ROMANIZED_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 549,
max => 'M',
min => 0,
pointer => !!0,
tag => 'ROMN',
value => '<PLACE_ROMANIZED_VARIATION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 552,
max => 1,
min => 1,
pointer => !!0,
tag => 'LATI',
value => '<PLACE_LATITUDE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 553,
max => 1,
min => 1,
pointer => !!0,
tag => 'LONG',
value => '<PLACE_LONGITUDE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 551,
max => 1,
min => 0,
tag => 'MAP'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 554,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 545,
max => 1,
min => 1,
pointer => !!0,
tag => 'PLAC',
value => '<PLACE_VALUE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 543,
structure => 'PLACE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 561,
max => 1,
min => 0,
pointer => !!0,
tag => 'PAGE',
value => '<WHERE_WITHIN_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 563,
max => 1,
min => 0,
pointer => !!0,
tag => 'ROLE',
value => '<ROLE_IN_EVENT>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 562,
max => 1,
min => 0,
pointer => !!0,
tag => 'EVEN',
value => '<EVENT_TYPE_CITED_FROM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 565,
max => 1,
min => 0,
pointer => !!0,
tag => 'DATE',
value => '<ENTRY_RECORDING_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 567,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 568,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 566,
max => 'M',
min => 0,
pointer => !!0,
tag => 'TEXT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 564,
max => 1,
min => 0,
tag => 'DATA'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 569,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 570,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 571,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
tag => 'QUAY',
value => '<CERTAINTY_ASSESSMENT>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 560,
max => 1,
min => 1,
pointer => !!1,
tag => 'SOUR',
value => '<XREF:SOUR>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 574,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<SOURCE_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 575,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<SOURCE_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 577,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONC',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 578,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CONT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 576,
max => 'M',
min => 0,
pointer => !!0,
tag => 'TEXT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 579,
max => 'M',
min => 0,
pointer => !!0,
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 580,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 581,
max => 1,
min => 0,
pointer => !!0,
selection => 1,
tag => 'QUAY',
value => '<CERTAINTY_ASSESSMENT>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 573,
max => 1,
min => 1,
pointer => !!0,
tag => 'SOUR',
value => '<SOURCE_DESCRIPTION>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 557,
selection => 1,
structure => 'SOURCE_CITATION'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 588,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+2',
line => 590,
max => 1,
min => 0,
pointer => !!0,
tag => 'MEDI',
value => '<SOURCE_MEDIA_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 589,
max => 'M',
min => 0,
pointer => !!0,
tag => 'CALN',
value => '<SOURCE_CALL_NUMBER>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 587,
max => 1,
min => 1,
pointer => !!1,
tag => 'REPO',
value => '<XREF:REPO>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 585,
structure => 'SOURCE_REPOSITORY_CITATION'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 597,
max => 'M',
min => 0,
pointer => !!0,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 596,
max => 1,
min => 1,
pointer => !!1,
tag => 'FAMS',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 594,
structure => 'SPOUSE_TO_FAMILY_LINK'
}, 'Gedcom::Grammar' )
],
level => -2,
line => 0,
stored_item => undef,
version => '5.5.1'
}, 'Gedcom::Grammar' );
