# Copyright 1998-2013, Paul Johnson (paul@pjcj.net)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# This file was automatically generated from gedcom-5.5.grammar
# by Paul Johnson,,,
# on Thu Jan 24 00:38:43 2013

# Do not edit this file.
# Edit gedcom-5.5.grammar if changes need to be made.
# Edit parse_grammar or Makefile.PL to increase the legibility of this file.
# (Removal of the leading spaces nearly halves the size of the file.)

# Version 1.18 - 24th January 2013

use strict;

require 5.005;

package Gedcom::Grammar_5_5;

use vars qw($VERSION $grammar);
$VERSION = 1.18;

$grammar = bless( {
fh => \*Symbol::GEN0,
file => 'gedcom-5.5.grammar',
gedcom => {},
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => 0,
line => 32,
max => 1,
min => 1,
pointer => '',
value => '<<HEADER>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => 0,
line => 33,
max => 1,
min => 0,
pointer => '',
value => '<<SUBMISSION_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => 0,
line => 34,
max => 'M',
min => 0,
pointer => '',
value => '<<RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 35,
max => 1,
min => 1,
tag => 'TRLR'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 30,
structure => 'GEDCOM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 41,
max => 1,
min => 0,
pointer => '',
tag => 'VERS',
value => '<VERSION_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 42,
max => 1,
min => 0,
pointer => '',
tag => 'NAME',
value => '<NAME_OF_PRODUCT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 44,
max => 1,
min => 0,
pointer => '',
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 43,
max => 1,
min => 0,
pointer => '',
tag => 'CORP',
value => '<NAME_OF_BUSINESS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 46,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<PUBLICATION_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 47,
max => 1,
min => 0,
pointer => '',
tag => 'COPR',
value => '<COPYRIGHT_SOURCE_DATA>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 45,
max => 1,
min => 0,
pointer => '',
tag => 'DATA',
value => '<NAME_OF_SOURCE_DATA>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 40,
max => 1,
min => 1,
pointer => '',
tag => 'SOUR',
value => '<APPROVED_SYSTEM_ID>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 48,
max => 1,
min => 0,
pointer => '',
tag => 'DEST',
value => '<RECEIVING_SYSTEM_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 50,
max => 1,
min => 0,
pointer => '',
tag => 'TIME',
value => '<TIME_VALUE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 49,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<TRANSMISSION_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 51,
max => 1,
min => 1,
pointer => 1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 52,
max => 1,
min => 0,
pointer => 1,
tag => 'SUBN',
value => '<XREF:SUBN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 53,
max => 1,
min => 0,
pointer => '',
tag => 'FILE',
value => '<FILE_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 54,
max => 1,
min => 0,
pointer => '',
tag => 'COPR',
value => '<COPYRIGHT_GEDCOM_FILE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 56,
max => 1,
min => 1,
pointer => '',
tag => 'VERS',
value => '<VERSION_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 57,
max => 1,
min => 1,
pointer => '',
tag => 'FORM',
value => '<GEDCOM_FORM>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 55,
max => 1,
min => 1,
tag => 'GEDC'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 59,
max => 1,
min => 0,
pointer => '',
tag => 'VERS',
value => '<VERSION_NUMBER>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 58,
max => 1,
min => 1,
pointer => '',
tag => 'CHAR',
value => '<CHARACTER_SET>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 60,
max => 1,
min => 0,
pointer => '',
tag => 'LANG',
value => '<LANGUAGE_OF_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 62,
max => 1,
min => 1,
pointer => '',
tag => 'FORM',
value => '<PLACE_HIERARCHY>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 61,
max => 1,
min => 0,
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 64,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<GEDCOM_CONTENT_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+2',
line => 65,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<GEDCOM_CONTENT_DESCRIPTION>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 63,
max => 1,
min => 0,
pointer => '',
tag => 'NOTE',
value => '<GEDCOM_CONTENT_DESCRIPTION>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 39,
max => 1,
min => 1,
tag => 'HEAD'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 37,
structure => 'HEADER'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 70,
max => 1,
min => 1,
pointer => '',
selection => 1,
value => '<<FAM_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 72,
max => 1,
min => 1,
pointer => '',
selection => 1,
value => '<<INDIVIDUAL_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 74,
max => 'M',
min => 1,
pointer => '',
selection => 1,
value => '<<MULTIMEDIA_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 76,
max => 1,
min => 1,
pointer => '',
selection => 1,
value => '<<NOTE_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 78,
max => 1,
min => 1,
pointer => '',
selection => 1,
value => '<<REPOSITORY_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 80,
max => 1,
min => 1,
pointer => '',
selection => 1,
value => '<<SOURCE_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 82,
max => 1,
min => 1,
pointer => '',
selection => 1,
value => '<<SUBMITTER_RECORD>>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 68,
selection => 1,
structure => 'RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 90,
max => 1,
min => 1,
pointer => '',
tag => 'AGE',
value => '<AGE_AT_EVENT>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 89,
max => 1,
min => 0,
tag => 'HUSB'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 92,
max => 1,
min => 1,
pointer => '',
tag => 'AGE',
value => '<AGE_AT_EVENT>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 91,
max => 1,
min => 0,
tag => 'WIFE'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 88,
max => 'M',
min => 0,
pointer => '',
value => '<<FAMILY_EVENT_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 93,
max => 1,
min => 0,
pointer => 1,
tag => 'HUSB',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 94,
max => 1,
min => 0,
pointer => 1,
tag => 'WIFE',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 95,
max => 'M',
min => 0,
pointer => 1,
tag => 'CHIL',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 96,
max => 1,
min => 0,
pointer => '',
tag => 'NCHI',
value => '<COUNT_OF_CHILDREN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 97,
max => 'M',
min => 0,
pointer => 1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 98,
max => 'M',
min => 0,
pointer => '',
value => '<<LDS_SPOUSE_SEALING>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 99,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 100,
max => 'M',
min => 0,
pointer => '',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 101,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 103,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 102,
max => 'M',
min => 0,
pointer => '',
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 104,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 105,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 87,
max => 1,
min => 1,
tag => 'FAM',
xref => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 85,
structure => 'FAM_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 111,
max => 1,
min => 0,
pointer => '',
tag => 'RESN',
value => '<RESTRICTION_NOTICE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 112,
max => 'M',
min => 0,
pointer => '',
value => '<<PERSONAL_NAME_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 113,
max => 1,
min => 0,
pointer => '',
tag => 'SEX',
value => '<SEX_VALUE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 114,
max => 'M',
min => 0,
pointer => '',
value => '<<INDIVIDUAL_EVENT_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 115,
max => 'M',
min => 0,
pointer => '',
value => '<<INDIVIDUAL_ATTRIBUTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 116,
max => 'M',
min => 0,
pointer => '',
value => '<<LDS_INDIVIDUAL_ORDINANCE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 117,
max => 'M',
min => 0,
pointer => '',
value => '<<CHILD_TO_FAMILY_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 118,
max => 'M',
min => 0,
pointer => '',
value => '<<SPOUSE_TO_FAMILY_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 119,
max => 'M',
min => 0,
pointer => 1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 120,
max => 'M',
min => 0,
pointer => '',
value => '<<ASSOCIATION_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 121,
max => 'M',
min => 0,
pointer => 1,
tag => 'ALIA',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 122,
max => 'M',
min => 0,
pointer => 1,
tag => 'ANCI',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 123,
max => 'M',
min => 0,
pointer => 1,
tag => 'DESI',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 124,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 125,
max => 'M',
min => 0,
pointer => '',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 126,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 127,
max => 1,
min => 0,
pointer => '',
tag => 'RFN',
value => '<PERMANENT_RECORD_FILE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 128,
max => 1,
min => 0,
pointer => '',
tag => 'AFN',
value => '<ANCESTRAL_FILE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 130,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 129,
max => 'M',
min => 0,
pointer => '',
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 131,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 132,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 110,
max => 1,
min => 1,
tag => 'INDI',
xref => '<XREF:INDI>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 108,
structure => 'INDIVIDUAL_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 138,
max => 1,
min => 1,
pointer => '',
tag => 'FORM',
value => '<MULTIMEDIA_FORMAT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 139,
max => 1,
min => 0,
pointer => '',
tag => 'TITL',
value => '<DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 140,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 142,
max => 'M',
min => 1,
pointer => '',
tag => 'CONT',
value => '<ENCODED_MULTIMEDIA_LINE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 141,
max => 1,
min => 1,
tag => 'BLOB'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 143,
max => 1,
min => 0,
pointer => 1,
tag => 'OBJE',
value => '<XREF:OBJE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 145,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 144,
max => 'M',
min => 0,
pointer => '',
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 146,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 147,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 137,
max => 1,
min => 1,
tag => 'OBJE',
xref => '<XREF:OBJE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 135,
structure => 'MULTIMEDIA_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 153,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 154,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 155,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 157,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 156,
max => 'M',
min => 0,
pointer => '',
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 158,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 159,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 152,
max => 1,
min => 1,
pointer => '',
tag => 'NOTE',
value => '<SUBMITTER_TEXT>',
xref => '<XREF:NOTE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 150,
structure => 'NOTE_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 165,
max => 1,
min => 0,
pointer => '',
tag => 'NAME',
value => '<NAME_OF_REPOSITORY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 166,
max => 1,
min => 0,
pointer => '',
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 167,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 169,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 168,
max => 'M',
min => 0,
pointer => '',
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 170,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 171,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 164,
max => 1,
min => 1,
tag => 'REPO',
xref => '<XREF:REPO>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 162,
structure => 'REPOSITORY_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 179,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_PERIOD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 180,
max => 1,
min => 0,
pointer => '',
tag => 'PLAC',
value => '<SOURCE_JURISDICTION_PLACE>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 178,
max => 'M',
min => 0,
pointer => '',
tag => 'EVEN',
value => '<EVENTS_RECORDED>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 181,
max => 1,
min => 0,
pointer => '',
tag => 'AGNC',
value => '<RESPONSIBLE_AGENCY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 182,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 177,
max => 1,
min => 0,
tag => 'DATA'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 184,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<SOURCE_ORIGINATOR>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 185,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<SOURCE_ORIGINATOR>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 183,
max => 1,
min => 0,
pointer => '',
tag => 'AUTH',
value => '<SOURCE_ORIGINATOR>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 187,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<SOURCE_DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 188,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<SOURCE_DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 186,
max => 1,
min => 0,
pointer => '',
tag => 'TITL',
value => '<SOURCE_DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 189,
max => 1,
min => 0,
pointer => '',
tag => 'ABBR',
value => '<SOURCE_FILED_BY_ENTRY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 191,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<SOURCE_PUBLICATION_FACTS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 192,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<SOURCE_PUBLICATION_FACTS>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 190,
max => 1,
min => 0,
pointer => '',
tag => 'PUBL',
value => '<SOURCE_PUBLICATION_FACTS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 194,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 195,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 193,
max => 1,
min => 0,
pointer => '',
tag => 'TEXT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 196,
max => 1,
min => 0,
pointer => '',
value => '<<SOURCE_REPOSITORY_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 197,
max => 'M',
min => 0,
pointer => '',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 198,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 200,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<USER_REFERENCE_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 199,
max => 'M',
min => 0,
pointer => '',
tag => 'REFN',
value => '<USER_REFERENCE_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 201,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 202,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 176,
max => 1,
min => 1,
tag => 'SOUR',
xref => '<XREF:SOUR>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 174,
structure => 'SOURCE_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 208,
max => 1,
min => 0,
pointer => 1,
tag => 'SUBM',
value => '<XREF:SUBM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 209,
max => 1,
min => 0,
pointer => '',
tag => 'FAMF',
value => '<NAME_OF_FAMILY_FILE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 210,
max => 1,
min => 0,
pointer => '',
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 211,
max => 1,
min => 0,
pointer => '',
tag => 'ANCE',
value => '<GENERATIONS_OF_ANCESTORS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 212,
max => 1,
min => 0,
pointer => '',
tag => 'DESC',
value => '<GENERATIONS_OF_DESCENDANTS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 213,
max => 1,
min => 0,
pointer => '',
tag => 'ORDI',
value => '<ORDINANCE_PROCESS_FLAG>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 214,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 207,
max => 1,
min => 1,
tag => 'SUBN',
xref => '<XREF:SUBN>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 205,
structure => 'SUBMISSION_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 220,
max => 1,
min => 1,
pointer => '',
tag => 'NAME',
value => '<SUBMITTER_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 221,
max => 1,
min => 0,
pointer => '',
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 222,
max => 'M',
min => 0,
pointer => '',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 223,
max => 3,
min => 0,
pointer => '',
tag => 'LANG',
value => '<LANGUAGE_PREFERENCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 224,
max => 1,
min => 0,
pointer => '',
tag => 'RFN',
value => '<SUBMITTER_REGISTERED_RFN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 225,
max => 1,
min => 0,
pointer => '',
tag => 'RIN',
value => '<AUTOMATED_RECORD_ID>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 226,
max => 1,
min => 0,
pointer => '',
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 219,
max => 1,
min => 1,
tag => 'SUBM',
xref => '<XREF:SUBM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 217,
structure => 'SUBMITTER_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 232,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<ADDRESS_LINE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 233,
max => 1,
min => 0,
pointer => '',
tag => 'ADR1',
value => '<ADDRESS_LINE1>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 234,
max => 1,
min => 0,
pointer => '',
tag => 'ADR2',
value => '<ADDRESS_LINE2>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 235,
max => 1,
min => 0,
pointer => '',
tag => 'CITY',
value => '<ADDRESS_CITY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 236,
max => 1,
min => 0,
pointer => '',
tag => 'STAE',
value => '<ADDRESS_STATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 237,
max => 1,
min => 0,
pointer => '',
tag => 'POST',
value => '<ADDRESS_POSTAL_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 238,
max => 1,
min => 0,
pointer => '',
tag => 'CTRY',
value => '<ADDRESS_COUNTRY>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 231,
max => 1,
min => 0,
pointer => '',
tag => 'ADDR',
value => '<ADDRESS_LINE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 239,
max => 3,
min => 0,
pointer => '',
tag => 'PHON',
value => '<PHONE_NUMBER>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 229,
structure => 'ADDRESS_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 245,
max => 1,
min => 1,
pointer => '',
tag => 'TYPE',
value => '<RECORD_TYPE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 246,
max => 1,
min => 1,
pointer => '',
tag => 'RELA',
value => '<RELATION_IS_DESCRIPTOR>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 247,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 248,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 244,
max => 'M',
min => 0,
pointer => 1,
tag => 'ASSO',
value => '<XREF:INDI>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 242,
structure => 'ASSOCIATION_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 255,
max => 1,
min => 0,
pointer => '',
tag => 'TIME',
value => '<TIME_VALUE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 254,
max => 1,
min => 1,
pointer => '',
tag => 'DATE',
value => '<CHANGE_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 256,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 253,
max => 1,
min => 1,
tag => 'CHAN'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 251,
structure => 'CHANGE_DATE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 262,
max => 'M',
min => 0,
pointer => '',
tag => 'PEDI',
value => '<PEDIGREE_LINKAGE_TYPE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 263,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 261,
max => 1,
min => 1,
pointer => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 259,
structure => 'CHILD_TO_FAMILY_LINK'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 268,
max => 1,
min => 0,
pointer => '',
tag => 'TYPE',
value => '<EVENT_DESCRIPTOR>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 269,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_VALUE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 270,
max => 1,
min => 0,
pointer => '',
value => '<<PLACE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 271,
max => 1,
min => 0,
pointer => '',
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 272,
max => 1,
min => 0,
pointer => '',
tag => 'AGE',
value => '<AGE_AT_EVENT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 273,
max => 1,
min => 0,
pointer => '',
tag => 'AGNC',
value => '<RESPONSIBLE_AGENCY>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 274,
max => 1,
min => 0,
pointer => '',
tag => 'CAUS',
value => '<CAUSE_OF_EVENT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 275,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 276,
max => 'M',
min => 0,
pointer => '',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => 0,
line => 277,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 266,
structure => 'EVENT_DETAIL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 285,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 284,
max => 1,
min => 1,
tag => 'ANUL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 288,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 287,
max => 1,
min => 1,
tag => 'CENS'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 291,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 290,
max => 1,
min => 1,
tag => 'DIV'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 294,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 293,
max => 1,
min => 1,
tag => 'DIVF'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 297,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 296,
max => 1,
min => 1,
tag => 'ENGA'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 300,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 299,
max => 1,
min => 1,
tag => 'MARR'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 303,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 302,
max => 1,
min => 1,
tag => 'MARB'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 306,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 305,
max => 1,
min => 1,
tag => 'MARC'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 309,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 308,
max => 1,
min => 1,
tag => 'MARL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 312,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 311,
max => 1,
min => 1,
tag => 'MARS'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 315,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 314,
max => 1,
min => 1,
tag => 'EVEN'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 281,
selection => 1,
structure => 'FAMILY_EVENT_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 324,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 323,
max => 1,
min => 1,
pointer => '',
tag => 'CAST',
value => '<CASTE_NAME>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 327,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 326,
max => 1,
min => 1,
pointer => '',
tag => 'DSCR',
value => '<PHYSICAL_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 330,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 329,
max => 1,
min => 1,
pointer => '',
tag => 'EDUC',
value => '<SCHOLASTIC_ACHIEVEMENT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 333,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 332,
max => 1,
min => 1,
pointer => '',
tag => 'IDNO',
value => '<NATIONAL_ID_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 336,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 335,
max => 1,
min => 1,
pointer => '',
tag => 'NATI',
value => '<NATIONAL_OR_TRIBAL_ORIGIN>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 339,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 338,
max => 1,
min => 1,
pointer => '',
tag => 'NCHI',
value => '<COUNT_OF_CHILDREN>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 342,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 341,
max => 1,
min => 1,
pointer => '',
tag => 'NMR',
value => '<COUNT_OF_MARRIAGES>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 345,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 344,
max => 1,
min => 1,
pointer => '',
tag => 'OCCU',
value => '<OCCUPATION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 348,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 347,
max => 1,
min => 1,
pointer => '',
tag => 'PROP',
value => '<POSSESSIONS>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 351,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 350,
max => 1,
min => 1,
pointer => '',
tag => 'RELI',
value => '<RELIGIOUS_AFFILIATION>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 354,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 353,
max => 1,
min => 1,
tag => 'RESI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 357,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 356,
max => 1,
min => 0,
pointer => '',
tag => 'SSN',
value => '<SOCIAL_SECURITY_NUMBER>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 360,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 359,
max => 1,
min => 1,
pointer => '',
tag => 'TITL',
value => '<NOBILITY_TYPE_TITLE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 320,
selection => 1,
structure => 'INDIVIDUAL_ATTRIBUTE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 368,
max => 1,
min => 0,
pointer => '',
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 369,
max => 1,
min => 0,
pointer => 1,
selection => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 367,
max => 1,
min => 1,
tag => 'BIRT'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 372,
max => 1,
min => 0,
pointer => '',
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 373,
max => 1,
min => 0,
pointer => 1,
selection => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 371,
max => 1,
min => 1,
tag => 'CHR'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 376,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 375,
max => 1,
min => 1,
tag => 'DEAT'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 379,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 378,
max => 1,
min => 1,
tag => 'BURI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 382,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 381,
max => 1,
min => 1,
tag => 'CREM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 385,
max => 1,
min => 0,
pointer => '',
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+2',
line => 387,
max => 1,
min => 0,
pointer => '',
selection => 1,
tag => 'ADOP',
value => '<ADOPTED_BY_WHICH_PARENT>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 386,
max => 1,
min => 0,
pointer => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 384,
max => 1,
min => 1,
tag => 'ADOP'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 390,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 389,
max => 1,
min => 1,
tag => 'BAPM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 393,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 392,
max => 1,
min => 1,
tag => 'BARM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 396,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 395,
max => 1,
min => 1,
tag => 'BASM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 399,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 398,
max => 1,
min => 1,
tag => 'BLES'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 402,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 401,
max => 1,
min => 1,
tag => 'CHRA'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 405,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 404,
max => 1,
min => 1,
tag => 'CONF'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 408,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 407,
max => 1,
min => 1,
tag => 'FCOM'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 411,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 410,
max => 1,
min => 1,
tag => 'ORDN'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 414,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 413,
max => 1,
min => 1,
tag => 'NATU'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 417,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 416,
max => 1,
min => 1,
tag => 'EMIG'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 420,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 419,
max => 1,
min => 1,
tag => 'IMMI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 423,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 422,
max => 1,
min => 1,
tag => 'CENS'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 426,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 425,
max => 1,
min => 1,
tag => 'PROB'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 429,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 428,
max => 1,
min => 1,
tag => 'WILL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 432,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 431,
max => 1,
min => 1,
tag => 'GRAD'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 435,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 434,
max => 1,
min => 1,
tag => 'RETI'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 438,
max => 1,
min => 0,
pointer => '',
selection => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 437,
max => 1,
min => 1,
tag => 'EVEN'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 364,
selection => 1,
structure => 'INDIVIDUAL_EVENT_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 446,
max => 1,
min => 0,
pointer => '',
tag => 'STAT',
value => '<LDS_BAPTISM_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 447,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 448,
max => 1,
min => 0,
pointer => '',
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 449,
max => 1,
min => 0,
pointer => '',
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 450,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 451,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 445,
max => 1,
min => 1,
tag => 'BAPL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 454,
max => 1,
min => 0,
pointer => '',
tag => 'STAT',
value => '<LDS_BAPTISM_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 455,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 456,
max => 1,
min => 0,
pointer => '',
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 457,
max => 1,
min => 0,
pointer => '',
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 458,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 459,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 453,
max => 1,
min => 1,
tag => 'CONL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 462,
max => 1,
min => 0,
pointer => '',
tag => 'STAT',
value => '<LDS_ENDOWMENT_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 463,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 464,
max => 1,
min => 0,
pointer => '',
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 465,
max => 1,
min => 0,
pointer => '',
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 466,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 467,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 461,
max => 1,
min => 1,
tag => 'ENDL'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 470,
max => 1,
min => 0,
pointer => '',
tag => 'STAT',
value => '<LDS_CHILD_SEALING_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 471,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 472,
max => 1,
min => 0,
pointer => '',
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 473,
max => 1,
min => 0,
pointer => '',
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 474,
max => 1,
min => 1,
pointer => 1,
tag => 'FAMC',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 475,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 476,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 469,
max => 1,
min => 1,
tag => 'SLGC'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 442,
selection => 1,
structure => 'LDS_INDIVIDUAL_ORDINANCE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 483,
max => 1,
min => 0,
pointer => '',
tag => 'STAT',
value => '<LDS_SPOUSE_SEALING_DATE_STATUS>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 484,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<DATE_LDS_ORD>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 485,
max => 1,
min => 0,
pointer => '',
tag => 'TEMP',
value => '<TEMPLE_CODE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 486,
max => 1,
min => 0,
pointer => '',
tag => 'PLAC',
value => '<PLACE_LIVING_ORDINANCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 487,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 488,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 482,
max => 1,
min => 1,
tag => 'SLGS'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 480,
structure => 'LDS_SPOUSE_SEALING'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => 0,
line => 494,
max => 1,
min => 1,
pointer => 1,
selection => 1,
tag => 'OBJE',
value => '<XREF:OBJE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 497,
max => 1,
min => 1,
pointer => '',
tag => 'FORM',
value => '<MULTIMEDIA_FORMAT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 498,
max => 1,
min => 0,
pointer => '',
tag => 'TITL',
value => '<DESCRIPTIVE_TITLE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 499,
max => 1,
min => 1,
pointer => '',
tag => 'FILE',
value => '<MULTIMEDIA_FILE_REFERENCE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 500,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 496,
max => 1,
min => 1,
tag => 'OBJE'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 491,
selection => 1,
structure => 'MULTIMEDIA_LINK'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+1',
line => 508,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 507,
max => 1,
min => 1,
pointer => 1,
tag => 'NOTE',
value => '<XREF:NOTE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 511,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 512,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 513,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 510,
max => 1,
min => 1,
pointer => '',
tag => 'NOTE',
value => '<SUBMITTER_TEXT>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 504,
selection => 1,
structure => 'NOTE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 520,
max => 1,
min => 0,
pointer => '',
tag => 'NPFX',
value => '<NAME_PIECE_PREFIX>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 521,
max => 1,
min => 0,
pointer => '',
tag => 'GIVN',
value => '<NAME_PIECE_GIVEN>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 522,
max => 1,
min => 0,
pointer => '',
tag => 'NICK',
value => '<NAME_PIECE_NICKNAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 523,
max => 1,
min => 0,
pointer => '',
tag => 'SPFX',
value => '<NAME_PIECE_SURNAME_PREFIX>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 524,
max => 1,
min => 0,
pointer => '',
tag => 'SURN',
value => '<NAME_PIECE_SURNAME>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 525,
max => 1,
min => 0,
pointer => '',
tag => 'NSFX',
value => '<NAME_PIECE_SUFFIX>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 526,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 527,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 519,
max => 1,
min => 1,
pointer => '',
tag => 'NAME',
value => '<NAME_PERSONAL>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 517,
structure => 'PERSONAL_NAME_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 533,
max => 1,
min => 0,
pointer => '',
tag => 'FORM',
value => '<PLACE_HIERARCHY>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 534,
max => 'M',
min => 0,
pointer => '',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 535,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 532,
max => 1,
min => 1,
pointer => '',
tag => 'PLAC',
value => '<PLACE_VALUE>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 530,
structure => 'PLACE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 542,
max => 1,
min => 0,
pointer => '',
tag => 'PAGE',
value => '<WHERE_WITHIN_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 544,
max => 1,
min => 0,
pointer => '',
tag => 'ROLE',
value => '<ROLE_IN_EVENT>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 543,
max => 1,
min => 0,
pointer => '',
tag => 'EVEN',
value => '<EVENT_TYPE_CITED_FROM>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 546,
max => 1,
min => 0,
pointer => '',
tag => 'DATE',
value => '<ENTRY_RECORDING_DATE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 548,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+3',
line => 549,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+2',
line => 547,
max => 'M',
min => 0,
pointer => '',
tag => 'TEXT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 545,
max => 1,
min => 0,
tag => 'DATA'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 550,
max => 1,
min => 0,
pointer => '',
tag => 'QUAY',
value => '<CERTAINTY_ASSESSMENT>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 551,
max => 'M',
min => 0,
pointer => '',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 552,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 541,
max => 1,
min => 1,
pointer => 1,
tag => 'SOUR',
value => '<XREF:SOUR>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 555,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<SOURCE_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 556,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<SOURCE_DESCRIPTION>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 558,
max => 'M',
min => 0,
pointer => '',
tag => 'CONC',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+2',
line => 559,
max => 'M',
min => 0,
pointer => '',
tag => 'CONT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 557,
max => 'M',
min => 0,
pointer => '',
tag => 'TEXT',
value => '<TEXT_FROM_SOURCE>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [],
level => '+1',
line => 560,
max => 'M',
min => 0,
pointer => '',
selection => 1,
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 554,
max => 1,
min => 1,
pointer => '',
tag => 'SOUR',
value => '<SOURCE_DESCRIPTION>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 538,
selection => 1,
structure => 'SOURCE_CITATION'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 567,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
file => '*',
items => [
bless( {
file => '*',
items => [],
level => '+2',
line => 569,
max => 1,
min => 0,
pointer => '',
tag => 'MEDI',
value => '<SOURCE_MEDIA_TYPE>'
}, 'Gedcom::Grammar' )
],
level => '+1',
line => 568,
max => 'M',
min => 0,
pointer => '',
tag => 'CALN',
value => '<SOURCE_CALL_NUMBER>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 566,
max => 1,
min => 1,
pointer => 1,
tag => 'REPO',
value => '<XREF:REPO>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 564,
structure => 'SOURCE_REPOSITORY_CITATION'
}, 'Gedcom::Grammar' ),
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [
bless( {
_items => 1,
file => '*',
gedcom => {},
items => [],
level => '+1',
line => 576,
max => 'M',
min => 0,
pointer => '',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
level => 0,
line => 575,
max => 1,
min => 1,
pointer => 1,
tag => 'FAMS',
value => '<XREF:FAM>'
}, 'Gedcom::Grammar' )
],
level => -1,
line => 573,
structure => 'SPOUSE_TO_FAMILY_LINK'
}, 'Gedcom::Grammar' )
],
level => -2,
line => 0,
stored_item => undef,
version => '5.5'
}, 'Gedcom::Grammar' );
