# Copyright 1998-1999, Paul Johnson (pjcj@transeda.com)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.transeda.com/pjcj

# This file was automatically generated from gedcom-5.5.grammar
# by Paul Johnson
# on Sun Jul 18 22:26:56 1999

# Do not edit this file.
# Edit gedcom-5.5.grammar if changes need to be made.
# Edit parse_grammar or Makefile.PL to increase the legibility of this file.
# (Removal of the leading spaces nearly halves the size of the file.)

# Version 1.05 - 20th July 1999

use strict;

require 5.005;

package Gedcom::Grammar_5_5;

use vars qw($VERSION $grammar);
$VERSION = "1.05";

$grammar = bless( {
level => -1,
children => [
bless( {
level => -1,
line => 1,
children => [
bless( {
level => '0',
min => 1,
line => 3,
children => [],
max => 1,
value => '<<HEADER>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 4,
children => [],
max => 1,
value => '<<SUBMISSION_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 5,
children => [],
max => 'M',
value => '<<RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 6,
children => [],
max => 1,
tag => 'TRLR'
}, 'Gedcom::Grammar' )
],
structure => 'GEDCOM'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 8,
children => [
bless( {
level => '0',
min => 1,
line => 10,
children => [
bless( {
level => '+1',
min => 1,
line => 11,
children => [
bless( {
level => '+2',
min => '0',
line => 12,
children => [],
max => 1,
value => '<VERSION_NUMBER>',
tag => 'VERS'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 13,
children => [],
max => 1,
value => '<NAME_OF_PRODUCT>',
tag => 'NAME'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 14,
children => [
bless( {
level => '+3',
min => '0',
line => 15,
children => [],
max => 1,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<NAME_OF_BUSINESS>',
tag => 'CORP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 16,
children => [
bless( {
level => '+3',
min => '0',
line => 17,
children => [],
max => 1,
value => '<PUBLICATION_DATE>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+3',
min => '0',
line => 18,
children => [],
max => 1,
value => '<COPYRIGHT_SOURCE_DATA>',
tag => 'COPR'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<NAME_OF_SOURCE_DATA>',
tag => 'DATA'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<APPROVED_SYSTEM_ID>',
tag => 'SOUR'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 19,
children => [],
max => 1,
value => '<RECEIVING_SYSTEM_NAME>',
tag => 'DEST'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 20,
children => [
bless( {
level => '+2',
min => '0',
line => 21,
children => [],
max => 1,
value => '<TIME_VALUE>',
tag => 'TIME'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<TRANSMISSION_DATE>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 22,
children => [],
max => 1,
value => '@<XREF:SUBM>@',
tag => 'SUBM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 23,
children => [],
max => 1,
value => '@<XREF:SUBN>@',
tag => 'SUBN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 24,
children => [],
max => 1,
value => '<FILE_NAME>',
tag => 'FILE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 25,
children => [],
max => 1,
value => '<COPYRIGHT_GEDCOM_FILE>',
tag => 'COPR'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 26,
children => [
bless( {
level => '+2',
min => 1,
line => 27,
children => [],
max => 1,
value => '<VERSION_NUMBER>',
tag => 'VERS'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => 1,
line => 28,
children => [],
max => 1,
value => '<GEDCOM_FORM>',
tag => 'FORM'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'GEDC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 29,
children => [
bless( {
level => '+2',
min => '0',
line => 30,
children => [],
max => 1,
value => '<VERSION_NUMBER>',
tag => 'VERS'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<CHARACTER_SET>',
tag => 'CHAR'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 31,
children => [],
max => 1,
value => '<LANGUAGE_OF_TEXT>',
tag => 'LANG'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 32,
children => [
bless( {
level => '+2',
min => 1,
line => 33,
children => [],
max => 1,
value => '<PLACE_HIERARCHY>',
tag => 'FORM'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 34,
children => [
bless( {
level => '+2',
min => '0',
line => 35,
children => [],
max => 'M',
value => '<GEDCOM_CONTENT_DESCRIPTION>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 36,
children => [],
max => 'M',
value => '<GEDCOM_CONTENT_DESCRIPTION>',
tag => 'CONC'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<GEDCOM_CONTENT_DESCRIPTION>',
tag => 'NOTE'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'HEAD'
}, 'Gedcom::Grammar' )
],
structure => 'HEADER'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 39,
children => [
bless( {
level => '0',
selection => 1,
min => 1,
line => 41,
children => [],
max => 1,
value => '<<FAM_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
selection => 1,
min => 1,
line => 43,
children => [],
max => 1,
value => '<<INDIVIDUAL_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
selection => 1,
min => 1,
line => 45,
children => [],
max => 'M',
value => '<<MULTIMEDIA_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
selection => 1,
min => 1,
line => 47,
children => [],
max => 1,
value => '<<NOTE_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
selection => 1,
min => 1,
line => 49,
children => [],
max => 1,
value => '<<REPOSITORY_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
selection => 1,
min => 1,
line => 51,
children => [],
max => 1,
value => '<<SOURCE_RECORD>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
selection => 1,
min => 1,
line => 53,
children => [],
max => 1,
value => '<<SUBMITTER_RECORD>>'
}, 'Gedcom::Grammar' )
],
structure => 'RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 56,
children => [
bless( {
level => '0',
min => 1,
line => 58,
children => [
bless( {
level => '+1',
min => '0',
line => 59,
children => [
bless( {
level => '+2',
min => '0',
line => 60,
children => [
bless( {
level => '+3',
min => 1,
line => 61,
children => [],
max => 1,
value => '<AGE_AT_EVENT>',
tag => 'AGE'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'HUSB'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 62,
children => [
bless( {
level => '+3',
min => 1,
line => 63,
children => [],
max => 1,
value => '<AGE_AT_EVENT>',
tag => 'AGE'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'WIFE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<<FAMILY_EVENT_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 64,
children => [],
max => 1,
value => '@<XREF:INDI>@',
tag => 'HUSB'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 65,
children => [],
max => 1,
value => '@<XREF:INDI>@',
tag => 'WIFE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 66,
children => [],
max => 'M',
value => '@<XREF:INDI>@',
tag => 'CHIL'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 67,
children => [],
max => 1,
value => '<COUNT_OF_CHILDREN>',
tag => 'NCHI'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 68,
children => [],
max => 'M',
value => '@<XREF:SUBM>@',
tag => 'SUBM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 69,
children => [],
max => 'M',
value => '<<LDS_SPOUSE_SEALING>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 70,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 71,
children => [],
max => 'M',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 72,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 73,
children => [
bless( {
level => '+2',
min => '0',
line => 74,
children => [],
max => 1,
value => '<USER_REFERENCE_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<USER_REFERENCE_NUMBER>',
tag => 'REFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 75,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 76,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:FAM>@',
tag => 'FAM'
}, 'Gedcom::Grammar' )
],
structure => 'FAM_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 79,
children => [
bless( {
level => '0',
min => 1,
line => 81,
children => [
bless( {
level => '+1',
min => '0',
line => 82,
children => [],
max => 1,
value => '<RESTRICTION_NOTICE>',
tag => 'RESN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 83,
children => [],
max => 'M',
value => '<<PERSONAL_NAME_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 84,
children => [],
max => 1,
value => '<SEX_VALUE>',
tag => 'SEX'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 85,
children => [],
max => 'M',
value => '<<INDIVIDUAL_EVENT_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 86,
children => [],
max => 'M',
value => '<<INDIVIDUAL_ATTRIBUTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 87,
children => [],
max => 'M',
value => '<<LDS_INDIVIDUAL_ORDINANCE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 88,
children => [],
max => 'M',
value => '<<CHILD_TO_FAMILY_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 89,
children => [],
max => 'M',
value => '<<SPOUSE_TO_FAMILY_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 90,
children => [],
max => 'M',
value => '@<XREF:SUBM>@',
tag => 'SUBM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 91,
children => [],
max => 'M',
value => '<<ASSOCIATION_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 92,
children => [],
max => 'M',
value => '@<XREF:INDI>@',
tag => 'ALIA'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 93,
children => [],
max => 'M',
value => '@<XREF:SUBM>@',
tag => 'ANCI'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 94,
children => [],
max => 'M',
value => '@<XREF:SUBM>@',
tag => 'DESI'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 95,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 96,
children => [],
max => 'M',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 97,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 98,
children => [],
max => 1,
value => '<PERMANENT_RECORD_FILE_NUMBER>',
tag => 'RFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 99,
children => [],
max => 1,
value => '<ANCESTRAL_FILE_NUMBER>',
tag => 'AFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 100,
children => [
bless( {
level => '+2',
min => '0',
line => 101,
children => [],
max => 1,
value => '<USER_REFERENCE_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<USER_REFERENCE_NUMBER>',
tag => 'REFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 102,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 103,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:INDI>@',
tag => 'INDI'
}, 'Gedcom::Grammar' )
],
structure => 'INDIVIDUAL_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 106,
children => [
bless( {
level => '0',
min => 1,
line => 108,
children => [
bless( {
level => '+1',
min => 1,
line => 109,
children => [],
max => 1,
value => '<MULTIMEDIA_FORMAT>',
tag => 'FORM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 110,
children => [],
max => 1,
value => '<DESCRIPTIVE_TITLE>',
tag => 'TITL'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 111,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 112,
children => [
bless( {
level => '+2',
min => 1,
line => 113,
children => [],
max => 'M',
value => '<ENCODED_MULTIMEDIA_LINE>',
tag => 'CONT'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BLOB'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 114,
children => [],
max => 1,
value => '@<XREF:OBJE>@',
tag => 'OBJE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 115,
children => [
bless( {
level => '+2',
min => '0',
line => 116,
children => [],
max => 1,
value => '<USER_REFERENCE_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<USER_REFERENCE_NUMBER>',
tag => 'REFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 117,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 118,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:OBJE>@',
tag => 'OBJE'
}, 'Gedcom::Grammar' )
],
structure => 'MULTIMEDIA_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 121,
children => [
bless( {
level => '0',
min => 1,
line => 123,
children => [
bless( {
level => '+1',
min => '0',
line => 124,
children => [],
max => 'M',
value => '<SUBMITTER_TEXT>',
tag => 'CONC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 125,
children => [],
max => 'M',
value => '<SUBMITTER_TEXT>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 126,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 127,
children => [
bless( {
level => '+2',
min => '0',
line => 128,
children => [],
max => 1,
value => '<USER_REFERENCE_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<USER_REFERENCE_NUMBER>',
tag => 'REFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 129,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 130,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:NOTE>@',
value => '<SUBMITTER_TEXT>',
tag => 'NOTE'
}, 'Gedcom::Grammar' )
],
structure => 'NOTE_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 133,
children => [
bless( {
level => '0',
min => 1,
line => 135,
children => [
bless( {
level => '+1',
min => '0',
line => 136,
children => [],
max => 1,
value => '<NAME_OF_REPOSITORY>',
tag => 'NAME'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 137,
children => [],
max => 1,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 138,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 139,
children => [
bless( {
level => '+2',
min => '0',
line => 140,
children => [],
max => 1,
value => '<USER_REFERENCE_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<USER_REFERENCE_NUMBER>',
tag => 'REFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 141,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 142,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:REPO>@',
tag => 'REPO'
}, 'Gedcom::Grammar' )
],
structure => 'REPOSITORY_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 145,
children => [
bless( {
level => '0',
min => 1,
line => 147,
children => [
bless( {
level => '+1',
min => '0',
line => 148,
children => [
bless( {
level => '+2',
min => '0',
line => 149,
children => [
bless( {
level => '+3',
min => '0',
line => 150,
children => [],
max => 1,
value => '<DATE_PERIOD>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+3',
min => '0',
line => 151,
children => [],
max => 1,
value => '<SOURCE_JURISDICTION_PLACE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<EVENTS_RECORDED>',
tag => 'EVEN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 152,
children => [],
max => 1,
value => '<RESPONSIBLE_AGENCY>',
tag => 'AGNC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 153,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'DATA'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 154,
children => [
bless( {
level => '+2',
min => '0',
line => 155,
children => [],
max => 'M',
value => '<SOURCE_ORIGINATOR>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 156,
children => [],
max => 'M',
value => '<SOURCE_ORIGINATOR>',
tag => 'CONC'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SOURCE_ORIGINATOR>',
tag => 'AUTH'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 157,
children => [
bless( {
level => '+2',
min => '0',
line => 158,
children => [],
max => 'M',
value => '<SOURCE_DESCRIPTIVE_TITLE>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 159,
children => [],
max => 'M',
value => '<SOURCE_DESCRIPTIVE_TITLE>',
tag => 'CONC'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SOURCE_DESCRIPTIVE_TITLE>',
tag => 'TITL'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 160,
children => [],
max => 1,
value => '<SOURCE_FILED_BY_ENTRY>',
tag => 'ABBR'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 161,
children => [
bless( {
level => '+2',
min => '0',
line => 162,
children => [],
max => 'M',
value => '<SOURCE_PUBLICATION_FACTS>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 163,
children => [],
max => 'M',
value => '<SOURCE_PUBLICATION_FACTS>',
tag => 'CONC'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SOURCE_PUBLICATION_FACTS>',
tag => 'PUBL'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 164,
children => [
bless( {
level => '+2',
min => '0',
line => 165,
children => [],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 166,
children => [],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'CONC'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<TEXT_FROM_SOURCE>',
tag => 'TEXT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 167,
children => [],
max => 1,
value => '<<SOURCE_REPOSITORY_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 168,
children => [],
max => 'M',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 169,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 170,
children => [
bless( {
level => '+2',
min => '0',
line => 171,
children => [],
max => 1,
value => '<USER_REFERENCE_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<USER_REFERENCE_NUMBER>',
tag => 'REFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 172,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 173,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:SOUR>@',
tag => 'SOUR'
}, 'Gedcom::Grammar' )
],
structure => 'SOURCE_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 176,
children => [
bless( {
level => '0',
min => 1,
line => 178,
children => [
bless( {
level => '+1',
min => '0',
line => 179,
children => [],
max => 1,
value => '@<XREF:SUBM>@',
tag => 'SUBM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 180,
children => [],
max => 1,
value => '<NAME_OF_FAMILY_FILE>',
tag => 'FAMF'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 181,
children => [],
max => 1,
value => '<TEMPLE_CODE>',
tag => 'TEMP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 182,
children => [],
max => 1,
value => '<GENERATIONS_OF_ANCESTORS>',
tag => 'ANCE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 183,
children => [],
max => 1,
value => '<GENERATIONS_OF_DESCENDANTS>',
tag => 'DESC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 184,
children => [],
max => 1,
value => '<ORDINANCE_PROCESS_FLAG>',
tag => 'ORDI'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 185,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:SUBN>@',
tag => 'SUBN'
}, 'Gedcom::Grammar' )
],
structure => 'SUBMISSION_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 188,
children => [
bless( {
level => '0',
min => 1,
line => 190,
children => [
bless( {
level => '+1',
min => 1,
line => 191,
children => [],
max => 1,
value => '<SUBMITTER_NAME>',
tag => 'NAME'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 192,
children => [],
max => 1,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 193,
children => [],
max => 'M',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 194,
children => [],
max => 3,
value => '<LANGUAGE_PREFERENCE>',
tag => 'LANG'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 195,
children => [],
max => 1,
value => '<SUBMITTER_REGISTERED_RFN>',
tag => 'RFN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 196,
children => [],
max => 1,
value => '<AUTOMATED_RECORD_ID>',
tag => 'RIN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 197,
children => [],
max => 1,
value => '<<CHANGE_DATE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
xref => '@<XREF:SUBM>@',
tag => 'SUBM'
}, 'Gedcom::Grammar' )
],
structure => 'SUBMITTER_RECORD'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 200,
children => [
bless( {
level => '0',
min => '0',
line => 202,
children => [
bless( {
level => '+1',
min => '0',
line => 203,
children => [],
max => 'M',
value => '<ADDRESS_LINE>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 204,
children => [],
max => 1,
value => '<ADDRESS_LINE1>',
tag => 'ADR1'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 205,
children => [],
max => 1,
value => '<ADDRESS_LINE2>',
tag => 'ADR2'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 206,
children => [],
max => 1,
value => '<ADDRESS_CITY>',
tag => 'CITY'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 207,
children => [],
max => 1,
value => '<ADDRESS_STATE>',
tag => 'STAE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 208,
children => [],
max => 1,
value => '<ADDRESS_POSTAL_CODE>',
tag => 'POST'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 209,
children => [],
max => 1,
value => '<ADDRESS_COUNTRY>',
tag => 'CTRY'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<ADDRESS_LINE>',
tag => 'ADDR'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 210,
children => [],
max => 3,
value => '<PHONE_NUMBER>',
tag => 'PHON'
}, 'Gedcom::Grammar' )
],
structure => 'ADDRESS_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 213,
children => [
bless( {
level => '0',
min => '0',
line => 215,
children => [
bless( {
level => '+1',
min => 1,
line => 216,
children => [],
max => 1,
value => '<RECORD_TYPE>',
tag => 'TYPE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 217,
children => [],
max => 1,
value => '<RELATION_IS_DESCRIPTOR>',
tag => 'RELA'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 218,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 219,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '@<XREF:INDI>@',
tag => 'ASSO'
}, 'Gedcom::Grammar' )
],
structure => 'ASSOCIATION_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 222,
children => [
bless( {
level => '0',
min => 1,
line => 224,
children => [
bless( {
level => '+1',
min => 1,
line => 225,
children => [
bless( {
level => '+2',
min => '0',
line => 226,
children => [],
max => 1,
value => '<TIME_VALUE>',
tag => 'TIME'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<CHANGE_DATE>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 227,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CHAN'
}, 'Gedcom::Grammar' )
],
structure => 'CHANGE_DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 230,
children => [
bless( {
level => '0',
min => 1,
line => 232,
children => [
bless( {
level => '+1',
min => '0',
line => 233,
children => [],
max => 'M',
value => '<PEDIGREE_LINKAGE_TYPE>',
tag => 'PEDI'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 234,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '@<XREF:FAM>@',
tag => 'FAMC'
}, 'Gedcom::Grammar' )
],
structure => 'CHILD_TO_FAMILY_LINK'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 237,
children => [
bless( {
level => '0',
min => '0',
line => 239,
children => [],
max => 1,
value => '<EVENT_DESCRIPTOR>',
tag => 'TYPE'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 240,
children => [],
max => 1,
value => '<DATE_VALUE>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 241,
children => [],
max => 1,
value => '<<PLACE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 242,
children => [],
max => 1,
value => '<<ADDRESS_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 243,
children => [],
max => 1,
value => '<AGE_AT_EVENT>',
tag => 'AGE'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 244,
children => [],
max => 1,
value => '<RESPONSIBLE_AGENCY>',
tag => 'AGNC'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 245,
children => [],
max => 1,
value => '<CAUSE_OF_EVENT>',
tag => 'CAUS'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 246,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 247,
children => [],
max => 'M',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 248,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
structure => 'EVENT_DETAIL'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 252,
children => [
bless( {
level => '0',
min => 1,
line => 255,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 256,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'ANUL'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 258,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 259,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CENS'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 261,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 262,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'DIV'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 264,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 265,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'DIVF'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 267,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 268,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'ENGA'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 270,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 271,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'MARR'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 273,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 274,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'MARB'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 276,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 277,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'MARC'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 279,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 280,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'MARL'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 282,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 283,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'MARS'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 285,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 286,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'EVEN'
}, 'Gedcom::Grammar' )
],
structure => 'FAMILY_EVENT_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 291,
children => [
bless( {
level => '0',
min => 1,
line => 294,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 295,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<CASTE_NAME>',
tag => 'CAST'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 297,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 298,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<PHYSICAL_DESCRIPTION>',
tag => 'DSCR'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 300,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 301,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SCHOLASTIC_ACHIEVEMENT>',
tag => 'EDUC'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 303,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 304,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<NATIONAL_ID_NUMBER>',
tag => 'IDNO'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 306,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 307,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<NATIONAL_OR_TRIBAL_ORIGIN>',
tag => 'NATI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 309,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 310,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<COUNT_OF_CHILDREN>',
tag => 'NCHI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 312,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 313,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<COUNT_OF_MARRIAGES>',
tag => 'NMR'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 315,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 316,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<OCCUPATION>',
tag => 'OCCU'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 318,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 319,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<POSSESSIONS>',
tag => 'PROP'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 321,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 322,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<RELIGIOUS_AFFILIATION>',
tag => 'RELI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 324,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 325,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'RESI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => '0',
line => 327,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 328,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SOCIAL_SECURITY_NUMBER>',
tag => 'SSN'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 330,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 331,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<NOBILITY_TYPE_TITLE>',
tag => 'TITL'
}, 'Gedcom::Grammar' )
],
structure => 'INDIVIDUAL_ATTRIBUTE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 335,
children => [
bless( {
level => '0',
min => 1,
line => 338,
children => [
bless( {
level => '+1',
min => '0',
line => 339,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 340,
children => [],
max => 1,
value => '@<XREF:FAM>@',
tag => 'FAMC'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BIRT'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 342,
children => [
bless( {
level => '+1',
min => '0',
line => 343,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 344,
children => [],
max => 1,
value => '@<XREF:FAM>@',
tag => 'FAMC'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CHR'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 346,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 347,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'DEAT'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 349,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 350,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BURI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 352,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 353,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CREM'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 355,
children => [
bless( {
level => '+1',
min => '0',
line => 356,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 357,
children => [
bless( {
level => '+2',
selection => 1,
min => '0',
line => 358,
children => [],
max => 1,
value => '<ADOPTED_BY_WHICH_PARENT>',
tag => 'ADOP'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '@<XREF:FAM>@',
tag => 'FAMC'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'ADOP'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 360,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 361,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BAPM'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 363,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 364,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BARM'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 366,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 367,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BASM'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 369,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 370,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BLES'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 372,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 373,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CHRA'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 375,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 376,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CONF'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 378,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 379,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'FCOM'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 381,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 382,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'ORDN'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 384,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 385,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'NATU'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 387,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 388,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'EMIG'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 390,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 391,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'IMMI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 393,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 394,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CENS'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 396,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 397,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'PROB'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 399,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 400,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'WILL'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 402,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 403,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'GRAD'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 405,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 406,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'RETI'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 408,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 409,
children => [],
max => 1,
value => '<<EVENT_DETAIL>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'EVEN'
}, 'Gedcom::Grammar' )
],
structure => 'INDIVIDUAL_EVENT_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 413,
children => [
bless( {
level => '0',
min => 1,
line => 416,
children => [
bless( {
level => '+1',
min => '0',
line => 417,
children => [],
max => 1,
value => '<LDS_BAPTISM_DATE_STATUS>',
tag => 'STAT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 418,
children => [],
max => 1,
value => '<DATE_LDS_ORD>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 419,
children => [],
max => 1,
value => '<TEMPLE_CODE>',
tag => 'TEMP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 420,
children => [],
max => 1,
value => '<PLACE_LIVING_ORDINANCE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 421,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 422,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'BAPL'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 424,
children => [
bless( {
level => '+1',
min => '0',
line => 425,
children => [],
max => 1,
value => '<LDS_BAPTISM_DATE_STATUS>',
tag => 'STAT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 426,
children => [],
max => 1,
value => '<DATE_LDS_ORD>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 427,
children => [],
max => 1,
value => '<TEMPLE_CODE>',
tag => 'TEMP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 428,
children => [],
max => 1,
value => '<PLACE_LIVING_ORDINANCE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 429,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 430,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'CONL'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 432,
children => [
bless( {
level => '+1',
min => '0',
line => 433,
children => [],
max => 1,
value => '<LDS_ENDOWMENT_DATE_STATUS>',
tag => 'STAT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 434,
children => [],
max => 1,
value => '<DATE_LDS_ORD>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 435,
children => [],
max => 1,
value => '<TEMPLE_CODE>',
tag => 'TEMP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 436,
children => [],
max => 1,
value => '<PLACE_LIVING_ORDINANCE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 437,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 438,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'ENDL'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 440,
children => [
bless( {
level => '+1',
min => '0',
line => 441,
children => [],
max => 1,
value => '<LDS_CHILD_SEALING_DATE_STATUS>',
tag => 'STAT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 442,
children => [],
max => 1,
value => '<DATE_LDS_ORD>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 443,
children => [],
max => 1,
value => '<TEMPLE_CODE>',
tag => 'TEMP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 444,
children => [],
max => 1,
value => '<PLACE_LIVING_ORDINANCE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 445,
children => [],
max => 1,
value => '@<XREF:FAM>@',
tag => 'FAMC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 446,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 447,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'SLGC'
}, 'Gedcom::Grammar' )
],
structure => 'LDS_INDIVIDUAL_ORDINANCE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 451,
children => [
bless( {
level => '0',
min => 1,
line => 453,
children => [
bless( {
level => '+1',
min => '0',
line => 454,
children => [],
max => 1,
value => '<LDS_SPOUSE_SEALING_DATE_STATUS>',
tag => 'STAT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 455,
children => [],
max => 1,
value => '<DATE_LDS_ORD>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 456,
children => [],
max => 1,
value => '<TEMPLE_CODE>',
tag => 'TEMP'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 457,
children => [],
max => 1,
value => '<PLACE_LIVING_ORDINANCE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 458,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 459,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'SLGS'
}, 'Gedcom::Grammar' )
],
structure => 'LDS_SPOUSE_SEALING'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 462,
children => [
bless( {
level => '0',
selection => 1,
min => 1,
line => 465,
children => [],
max => 1,
value => '@<XREF:OBJE>@',
tag => 'OBJE'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 467,
children => [
bless( {
level => '+1',
min => 1,
line => 468,
children => [],
max => 1,
value => '<MULTIMEDIA_FORMAT>',
tag => 'FORM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 469,
children => [],
max => 1,
value => '<DESCRIPTIVE_TITLE>',
tag => 'TITL'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => 1,
line => 470,
children => [],
max => 1,
value => '<MULTIMEDIA_FILE_REFERENCE>',
tag => 'FILE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 471,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'OBJE'
}, 'Gedcom::Grammar' )
],
structure => 'MULTIMEDIA_LINK'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 475,
children => [
bless( {
level => '0',
min => 1,
line => 478,
children => [
bless( {
level => '+1',
selection => 1,
min => '0',
line => 479,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '@<XREF:NOTE>@',
tag => 'NOTE'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 481,
children => [
bless( {
level => '+1',
min => '0',
line => 482,
children => [],
max => 'M',
value => '<SUBMITTER_TEXT>',
tag => 'CONC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 483,
children => [],
max => 'M',
value => '<SUBMITTER_TEXT>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 484,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SUBMITTER_TEXT>',
tag => 'NOTE'
}, 'Gedcom::Grammar' )
],
structure => 'NOTE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 488,
children => [
bless( {
level => '0',
min => 1,
line => 490,
children => [
bless( {
level => '+1',
min => '0',
line => 491,
children => [],
max => 1,
value => '<NAME_PIECE_PREFIX>',
tag => 'NPFX'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 492,
children => [],
max => 1,
value => '<NAME_PIECE_GIVEN>',
tag => 'GIVN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 493,
children => [],
max => 1,
value => '<NAME_PIECE_NICKNAME>',
tag => 'NICK'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 494,
children => [],
max => 1,
value => '<NAME_PIECE_SURNAME_PREFIX>',
tag => 'SPFX'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 495,
children => [],
max => 1,
value => '<NAME_PIECE_SURNAME>',
tag => 'SURN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 496,
children => [],
max => 1,
value => '<NAME_PIECE_SUFFIX>',
tag => 'NSFX'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 497,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 498,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<NAME_PERSONAL>',
tag => 'NAME'
}, 'Gedcom::Grammar' )
],
structure => 'PERSONAL_NAME_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 501,
children => [
bless( {
level => '0',
min => 1,
line => 503,
children => [
bless( {
level => '+1',
min => '0',
line => 504,
children => [],
max => 1,
value => '<PLACE_HIERARCHY>',
tag => 'FORM'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 505,
children => [],
max => 'M',
value => '<<SOURCE_CITATION>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 506,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<PLACE_VALUE>',
tag => 'PLAC'
}, 'Gedcom::Grammar' )
],
structure => 'PLACE_STRUCTURE'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
selection => 1,
line => 509,
children => [
bless( {
level => '0',
min => 1,
line => 512,
children => [
bless( {
level => '+1',
min => '0',
line => 513,
children => [],
max => 1,
value => '<WHERE_WITHIN_SOURCE>',
tag => 'PAGE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 514,
children => [
bless( {
level => '+2',
min => '0',
line => 515,
children => [],
max => 1,
value => '<ROLE_IN_EVENT>',
tag => 'ROLE'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<EVENT_TYPE_CITED_FROM>',
tag => 'EVEN'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 516,
children => [
bless( {
level => '+2',
min => '0',
line => 517,
children => [],
max => 1,
value => '<ENTRY_RECORDING_DATE>',
tag => 'DATE'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 518,
children => [
bless( {
level => '+3',
min => '0',
line => 519,
children => [],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'CONC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+3',
min => '0',
line => 520,
children => [],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'CONT'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'TEXT'
}, 'Gedcom::Grammar' )
],
max => 1,
tag => 'DATA'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 521,
children => [],
max => 1,
value => '<CERTAINTY_ASSESSMENT>',
tag => 'QUAY'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 522,
children => [],
max => 'M',
value => '<<MULTIMEDIA_LINK>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 523,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '@<XREF:SOUR>@',
tag => 'SOUR'
}, 'Gedcom::Grammar' ),
bless( {
level => '0',
min => 1,
line => 525,
children => [
bless( {
level => '+1',
min => '0',
line => 526,
children => [],
max => 'M',
value => '<SOURCE_DESCRIPTION>',
tag => 'CONC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 527,
children => [],
max => 'M',
value => '<SOURCE_DESCRIPTION>',
tag => 'CONT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 528,
children => [
bless( {
level => '+2',
min => '0',
line => 529,
children => [],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'CONC'
}, 'Gedcom::Grammar' ),
bless( {
level => '+2',
min => '0',
line => 530,
children => [],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'CONT'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<TEXT_FROM_SOURCE>',
tag => 'TEXT'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
selection => 1,
min => '0',
line => 531,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '<SOURCE_DESCRIPTION>',
tag => 'SOUR'
}, 'Gedcom::Grammar' )
],
structure => 'SOURCE_CITATION'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 535,
children => [
bless( {
level => '0',
min => 1,
line => 537,
children => [
bless( {
level => '+1',
min => '0',
line => 538,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' ),
bless( {
level => '+1',
min => '0',
line => 539,
children => [
bless( {
level => '+2',
min => '0',
line => 540,
children => [],
max => 1,
value => '<SOURCE_MEDIA_TYPE>',
tag => 'MEDI'
}, 'Gedcom::Grammar' )
],
max => 'M',
value => '<SOURCE_CALL_NUMBER>',
tag => 'CALN'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '@<XREF:REPO>@',
tag => 'REPO'
}, 'Gedcom::Grammar' )
],
structure => 'SOURCE_REPOSITORY_CITATION'
}, 'Gedcom::Grammar' ),
bless( {
level => -1,
line => 544,
children => [
bless( {
level => '0',
min => 1,
line => 546,
children => [
bless( {
level => '+1',
min => '0',
line => 547,
children => [],
max => 'M',
value => '<<NOTE_STRUCTURE>>'
}, 'Gedcom::Grammar' )
],
max => 1,
value => '@<XREF:FAM>@',
tag => 'FAMS'
}, 'Gedcom::Grammar' )
],
structure => 'SPOUSE_TO_FAMILY_LINK'
}, 'Gedcom::Grammar' )
],
file => 'gedcom-5.5.grammar'
}, 'Gedcom::Grammar' );
